// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpqkfdepywktxxgzrhfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwcWtmZGVweXdrdHh4Z3pyaGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDc3NzEsImV4cCI6MjA3NDcyMzc3MX0.OeP0DQfibYzMZbpZxLQR8DQhT7lF-gGZEPTEMNIijGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});